
/'
' Generated by Meld Framework, do not modify.  Any changes will be overwritten
' during the next build.
'/

#include once "../../../../../modules/headers/sys/sys-v1.bi"

dim shared _moduleLocal as Module.Interface
dim shared _module as Module.Interface ptr
dim shared _ as .Interface ptr

type ModuleStateType
	methods as .Interface
	isLoaded as short
	isStarted as short
end type

dim shared as ModuleStateType moduleState

namespace 


end namespace

