#!/bin/bash

echo Starting Meld Core build...
echo
echo Compiling modules...
echo

fbc -mt -c "./src/fb/meld/lib/core/core.bas" || { echo; echo Failed to compile core, build terminated; exit 1; }
fbc -mt -c "./src/fb/meld/lib/fault/fault.bas" || { echo; echo Failed to compile fault, build terminated; exit 1; }
fbc -mt -c "./src/fb/meld/lib/error-handling/error-handling.bas" || { echo; echo Failed to compile error-handling, build terminated; exit 1; }

fbc -mt -c "./src/fb/shared/lib/bst/bst.bas" || { echo; echo Failed to compile bst, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/console/console.bas" || { echo; echo Failed to compile console, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/identity/identity.bas" || { echo; echo Failed to compile identity, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/iterator/iterator.bas" || { echo; echo Failed to compile iterator, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/list/list.bas" || { echo; echo Failed to compile list, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/paged-array/paged-array.bas" || { echo; echo Failed to compile paged-array, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/resource-container/resource-container.bas" || { echo; echo Failed to compile resource-container, build terminated; exit 1; }

fbc -mt -C "./src/fb/tester/tester.bas" -x "./tester" \
	"./src/fb/meld/lib/core/core.o" \
	"./src/fb/meld/lib/fault/fault.o" \
	"./src/fb/meld/lib/error-handling/error-handling.o" \
	"./src/fb/shared/lib/bst/bst.o" \
	"./src/fb/shared/lib/console/console.o" \
	"./src/fb/shared/lib/identity/identity.o" \
	"./src/fb/shared/lib/iterator/iterator.o" \
	"./src/fb/shared/lib/list/list.o" \
	"./src/fb/shared/lib/paged-array/paged-array.o" \
	"./src/fb/shared/lib/resource-container/resource-container.o" \
	|| { echo; echo Test compilation failed, build terminated; exit 1; }

echo "";

./tester || { echo; echo Test failed, build terminated; exit 1; }

echo;
echo Building Meld Core...;

fbc -mt -C "./src/fb/meld/meld.bas" -x "./meld" \
	"./src/fb/meld/lib/core/core.o" \
	"./src/fb/meld/lib/fault/fault.o" \
	"./src/fb/meld/lib/error-handling/error-handling.o" \
	"./src/fb/shared/lib/bst/bst.o" \
	"./src/fb/shared/lib/console/console.o" \
	"./src/fb/shared/lib/identity/identity.o" \
	"./src/fb/shared/lib/iterator/iterator.o" \
	"./src/fb/shared/lib/list/list.o" \
	"./src/fb/shared/lib/paged-array/paged-array.o" \
	"./src/fb/shared/lib/resource-container/resource-container.o" \
	|| { echo; echo Build failed; exit 1; }

echo;
echo Build successful!;
