#!/bin/bash

echo Starting Meld Core build...
echo
echo Compiling modules...
echo

fbc -mt -c "./src/fb/shared/lib/identity/identity.bas" || { echo; echo Failed to compile identity, build terminated; exit 1; }
fbc -mt -c "./src/fb/shared/lib/paged-array/paged-array.bas" || { echo; echo Failed to compile paged-array, build terminated; exit 1; }

fbc -mt -C "./src/fb/tester/tester.bas" -x "./tester" \
	"./src/fb/shared/lib/identity/identity.o" \
	"./src/fb/shared/lib/paged-array/paged-array.o" \
	|| { echo; echo Test compilation failed, build terminated; exit 1; }

echo "";

./tester || { echo; echo Test failed, build terminated; exit 1; }

echo;
echo Building Meld Core...;

fbc -mt -C "./src/fb/meld/meld.bas" -x "./meld" \
	"./src/fb/shared/lib/identity/identity.o" \
	"./src/fb/shared/lib/paged-array/paged-array.o" \
	|| { echo; echo Build failed; exit 1; }

echo;
echo Build successful!;
