#!/bin/bash

# Get root directory of Meld
SOURCE="${BASH_SOURCE[0]}"

# If a symlink or chain of symlinks, iterate back to original directory
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

MELD_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
MODULE_NAME=${PWD##*/}

# Display help page if no arguments given
if [ $# -eq 0 ]; then
	$MELD_DIR/commands/help
	exit 0;
fi

# If 'run' argument passed, launch from commands directory, otherwise launch
# the given module passing all arguments to it
if [ -z "$1" ]; then
	echo "Missing run command"
	exit 1;
fi

if [ ! -f "$MELD_DIR/commands/$1" ]; then
	echo "Not a valid command"
	exit 1;
fi

if [ "$1" = "launch" ]; then
	$MELD_DIR/commands/launch "$MODULE_NAME" "$@"
else
	$MELD_DIR/commands/$1 "$MELD_DIR" "$MODULE_NAME" "$2"
fi

