#!/bin/bash

# Get root directory of Meld
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

MELD_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
MODULE_NAME=${PWD##*/}

# Display help page if no arguments given
if [ $# -eq 0 ]; then
	$MELD_DIR/commands/help
	exit 0;
fi

# If 'run' argument passed, launch from commands directory, otherwise launch
# the given module passing all arguments to it
if [ "$1" == "run" ]; then
	if [ -z "$2" ]; then
		echo "Missing run command"
		exit 1;
	fi

	if [ ! -f "$MELD_DIR/commands/$2" ]; then
		echo "Not a valid command"
		exit 1;
	fi

	$MELD_DIR/commands/$2 "$MELD_DIR" "$MODULE_NAME" "$@"
else
	$MELD_DIR/commands/launch "$@"
fi

