
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#include "headers/module_v0.1.0.bi"
#include "headers/fault_v0.1.0.bi"
#include "headers/sys_v0.1.0.bi"
#include "headers/console_v0.1.0.bi"

#define NULL 0

struct ModuleStateType {
	Console.Interface methods
	short isLoaded
	short isStarted
}

Module.Interface* _module
Console.Interface* _console
Fault.Interface* _fault
Sys.Interface* _sys
ModuleStateType moduleState

namespace Console {
	short __cdecl *startup ();
	short __cdecl *shutdown ();
	void __cdecl *logMessage (char* message);
	void __cdecl *logWarning (char* id, char* message, char* source, int lineNum);
	void __cdecl *logError (char* id, char* message, char* source, int lineNum);
	void __cdecl *logSuccess (char* id, char* message, char* source, int lineNum);
}

