
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */


#include <stdio>
#include "headers/console_v0.1.0.bi"
#include "console.bi"

Module.Interface _moduleLocal

extern "C" __cdecl (dllexport) void* exports ();
extern "C" __cdecl (dllexport) short load (Module.Interface * modulePtr);
extern "C" __cdecl (dllexport) short unload ();
extern "C" __cdecl (dllexport) short startup ();
extern "C" __cdecl (dllexport) short shutdown ();

extern "C" __cdecl (dllexport) void* exports () {
	moduleState.methods.startup = Console.startup
	moduleState.methods.shutdown = Console.shutdown
	moduleState.methods.logMessage = Console.logMessage
	moduleState.methods.logWarning = Console.logWarning
	moduleState.methods.logError = Console.logError
	moduleState.methods.logSuccess = Console.logSuccess

	return &moduleState.methods
}

extern "C" __cdecl (dllexport) short load (Module.Interface * modulePtr) {
	if (modulePtr == NULL) {
		printf("**** Console.load: Invalid Module interface pointer\n")
		return false
	}

	if (!moduleState.isLoaded) {
		moduleState.isStarted = false
		moduleState.isLoaded = true

		_moduleLocal = *modulePtr
		_module = &_moduleLocal

		_console = exports()

		_fault = (*modulePtr->require)("fault_v0.1.0")
		if (_fault == NULL) {
			printf("**** Console.load: Failed to load fault dependency")
			return false
		}

		_sys = (*modulePtr->require)("sys_v0.1.0")
		if (_sys == NULL) {
			printf("**** Console.load: Failed to load sys dependency")
			return false
		}
	}

	return true
}

extern "C" __cdecl (dllexport) short unload () {
	if (moduleState.isStarted) {
		if (moduleState.methods.shutdown != NULL) {
			if (!moduleState.methods.shutdown()) {
				printf("**** Console.unload: Module shutdown handler failed\n")
				return false
			}
		}

		moduleState.isStarted = false
	}

	moduleState.isLoaded = false

	return true
}

extern "C" __cdecl (dllexport) short startup () {
	if (!moduleState.isStarted) {
		if (moduleState.methods.startup != NULL) {
			if (!moduleState.methods.startup()) {
				printf("**** Console.startup: Module startup handler failed\n")
				return false
			}
		}

		moduleState.isStarted = true
	}

	return true
}

extern "C" __cdecl (dllexport) short shutdown () {
	if (moduleState.isStarted) {
		if (moduleState.methods.shutdown != NULL) {
			if (!moduleState.methods.shutdown()) {
				printf("**** Console.shutdown: Module shutdown handler failed\n")
			}
		}

		moduleState.isStarted = false
	}

	return true
}
