#!/bin/bash

# Config
source "$1/config/lang"

# Setup variables
MELD_DIR=$1
MODULE_NAME=$2

if [ -n "$3" ]; then
	LANG_SELECT=$3
else
	LANG_SELECT=$LANG_DEFAULT
fi

LANG_DIR="${LANG["$LANG_SELECT"]}"

# Check for selected source language
if [ ! -f "$MELD_DIR/$LANG_DIR/ext.cfg" ]; then
	echo Invalid source language: $LANG_SELECT;
	exit 1;
fi

# Load source language file extensions
while IFS=',' read -r LANG_SOURCE_EXT LANG_HEADER_EXT
do
	echo "$LANG_SOURCE_EXT";
	echo "$LANG_HEADER_EXT";
done < "$MELD_DIR/$LANG_DIR/ext.cfg"

# Create source and build directories if they don't already exist
if [ ! -d "./.meld" ]; then
	mkdir "./.meld"
	touch "./.meld/.gitkeep"
	touch "./.meld/deps"
fi

if [ ! -d "./src" ]; then
	mkdir "./src"
fi

if [ ! -d "./src/headers" ]; then
	mkdir "./src/headers"
	touch "./src/headers/.gitkeep"
fi

if [ ! -d "./bin" ]; then
	mkdir "./bin"
fi

if [ ! -L "./meld_modules" ]; then
	ln -s $MELD_DIR/modules/local ./meld_modules
fi

# Initialize XML file for templates to build from
if [ ! -f ./bin/module.xml ]; then
	echo -n "<?xml version=\"1.0\" encoding=\"UTF-8\"?><module name=\"$MODULE_NAME\"><namespace>" >> ./bin/module.xml
	"$MELD_DIR/build/kebab-to-pascal" $MODULE_NAME >> ./bin/module.xml
	echo "</namespace><version>0.1.0</version></module>" >> ./bin/module.xml
fi

# Generate one-time, user modifiable boilerplate
if [ ! -f ./src/$MODULE_NAME.$LANG_SOURCE_EXT ]; then
	xsltproc -o ./src/$MODULE_NAME.$LANG_SOURCE_EXT "$MELD_DIR/$LANG_DIR/templates/source.xslt" ./bin/module.xml
	xsltproc -o ./src/test.$LANG_HEADER_EXT "$MELD_DIR/$LANG_DIR/templates/test.xslt" ./bin/module.xml
	xsltproc -o ./src/errors.$LANG_HEADER_EXT "$MELD_DIR/$LANG_DIR/templates/errors.xslt" ./bin/module.xml
fi

# Generate dynamic source files, not modifiable by the user
xsltproc -o ./src/module.$LANG_HEADER_EXT "$MELD_DIR/$LANG_DIR/templates/module.xslt" ./bin/module.xml
xsltproc -o ./src/$MODULE_NAME.$LANG_HEADER_EXT "$MELD_DIR/$LANG_DIR/templates/include.xslt" ./bin/module.xml
xsltproc -o ./.meld/version "$MELD_DIR/build/templates/version.xslt" ./bin/module.xml
