#!/bin/bash

MELD_DIR=$1
MODULE_NAME=$2
MODULE_VERSION=$(<./.meld/version)
SEP="_v"
CURRENT=$(pwd)
TARGET=$(realpath "$CURRENT/bin")

# Check if already linked
if [ -f "./.meld/undo-link" ]; then
	./.meld/undo-link
	rm ./.meld/undo-link
fi

# Check if global install already exists and "remember" it
if [ -L "$MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION" ]; then
	ORIGINAL=$(readlink -f "$MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION")
	unlink $MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION
else
	ORIGINAL=""
fi

ln -s $TARGET $MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION

# Generate undo-link script to reliably remove link across version changes
echo "#!/bin/bash" > ./.meld/undo-link
echo "unlink $MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION" >> ./.meld/undo-link

# If replacing an existing link, restore it in the "undo" script
if [ "$ORIGINAL" != "" ] && [ "$TARGET" != "$ORIGINAL" ]; then
	echo "ln -s $ORIGINAL $MELD_DIR/modules/local/$MODULE_NAME$SEP$MODULE_VERSION" >> ./.meld/undo-link
fi

chmod +x ./.meld/undo-link
