
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */


#include <stdio.h>
#include "headers/test-c_v0.1.0.h"
#include "test-c.h"

Module::Interface _moduleLocal;

extern "C" void* exports () __attribute__((cdecl));
extern "C" short load (Module::Interface * modulePtr) __attribute__((cdecl));
extern "C" short unload () __attribute__((cdecl));

extern "C" short test () __attribute__((cdecl));

extern "C" short startup () __attribute__((cdecl));
extern "C" short shutdown () __attribute__((cdecl));

extern "C" void* exports () {
	
	moduleState.methods.startup = TestC::startup;
	moduleState.methods.shutdown = TestC::shutdown;
	moduleState.methods.test = TestC::test;
	moduleState.methods.sayHello = TestC::sayHello;

	return &moduleState.methods;
}

extern "C" short load (Module::Interface * modulePtr) {
	if (modulePtr == NULL) {
		printf("**** TestC::load: Invalid Module interface pointer\n");
		return FALSE;
	}

	if (!moduleState.isLoaded) {
		moduleState.isStarted = FALSE;
		moduleState.isLoaded = TRUE;

		_moduleLocal = *modulePtr;
		_module = &_moduleLocal;

		_testC = static_cast<TestC::Interface*>(exports());

		_sys = static_cast<Sys::Interface*>((*modulePtr->require)("sys_v0.1.0"));
		if (_sys == NULL) {
			printf("**** TestC.load: Failed to load sys dependency\n");
			return FALSE;
		}

		_console = static_cast<Console::Interface*>((*modulePtr->require)("console_v0.1.0"));
		if (_console == NULL) {
			printf("**** TestC.load: Failed to load console dependency\n");
			return FALSE;
		}

		_fault = static_cast<Fault::Interface*>((*modulePtr->require)("fault_v0.1.0"));
		if (_fault == NULL) {
			printf("**** TestC.load: Failed to load fault dependency\n");
			return FALSE;
		}

		_tester = static_cast<Tester::Interface*>((*modulePtr->require)("tester_v0.1.0"));
		if (_tester == NULL) {
			printf("**** TestC.load: Failed to load tester dependency\n");
			return FALSE;
		}



	}

	return TRUE;
}

extern "C" short unload () {
	if (moduleState.isStarted) {
		if (moduleState.methods.shutdown != NULL) {
			if (!moduleState.methods.shutdown()) {
				printf("**** TestC::unload: Module shutdown handler failed\n");
				return FALSE;
			}
		}

		moduleState.isStarted = FALSE;
	}

	moduleState.isLoaded = FALSE;

	return TRUE;
}


extern "C" short test () {
	TestC::Interface *interfacePtr = static_cast<TestC::Interface*>(exports());
	Tester::testModule tests[1];

	if (interfacePtr->test == NULL) {
		return TRUE;
	}

	tests[0] = interfacePtr->test;

	if (!_tester->run(tests, 1)) {
		return FALSE;
	}

	return TRUE;
}


extern "C" short startup () {
	if (!moduleState.isStarted) {
		if (moduleState.methods.startup != NULL) {
			if (!moduleState.methods.startup()) {
				printf("**** TestC::startup: Module startup handler failed\n");
				return FALSE;
			}
		}

		moduleState.isStarted = TRUE;
	}

	return TRUE;
}

extern "C" short shutdown () {
	if (moduleState.isStarted) {
		if (moduleState.methods.shutdown != NULL) {
			if (!moduleState.methods.shutdown()) {
				printf("**** TestC::shutdown: Module shutdown handler failed\n");
			}
		}

		moduleState.isStarted = FALSE;
	}

	return TRUE;
}
