
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

#include "headers/module_v0.1.0.h"
#include "headers/test-c_v0.1.0.h"

#ifndef NULL
#define NULL 0
#endif

#ifndef NULL
#define FALSE 0
#endif

#ifndef NULL
#define TRUE -1
#endif

#ifndef NULL
#define String char*
#endif

Module::Interface* _module;
Testc::Interface* _testc;

struct ModuleStateType {
	TestC::Interface methods;
	short isLoaded;
	short isStarted;
} moduleState;

namespace TestC {


}

