
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

#ifndef String
#define String char*
#endif

#ifndef NULL
#define NULL 0
#endif

#ifndef FALSE
#define FALSE 0
#endif

#ifndef TRUE
#define TRUE -1
#endif

#include "headers/module_v0.1.0.h"
#include "headers/sys_v0.1.0.h"
#include "headers/console_v0.1.0.h"
#include "headers/fault_v0.1.0.h"
#include "headers/tester_v0.1.0.h"
#include "headers/test-c_v0.1.0.h"

Module::Interface* _module;
TestC::Interface* _testC;
Sys::Interface* _sys;
Console::Interface* _console;
Fault::Interface* _fault;
Tester::Interface* _tester;

struct ModuleStateType {
	TestC::Interface methods;
	short isLoaded;
	short isStarted;
} moduleState;

namespace TestC {

short (*startup) () __attribute__((cdecl));
short (*shutdown) () __attribute__((cdecl));
short (*test) (void*  describeFn ) __attribute__((cdecl));

}

