
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

namespace Sys {


struct Interface {
	short (*startup) () __attribute__((cdecl));
	short (*shutdown) () __attribute__((cdecl));
	void* construct;
	void* destruct;
	void* update;
	void* test;
	char* (*getNewline) () __attribute__((cdecl));
	char* (*getDirsep) () __attribute__((cdecl));
	char* (*getModuleExt) () __attribute__((cdecl));
	unsigned long long (*getTimestamp) () __attribute__((cdecl));
	void (*getMacAddress) (char*  addr ) __attribute__((cdecl));
};

}
