
/'
 ' Generated by Meld Framework, do not modify.  Any changes will be overwritten
 ' during the next build.
 '/

namespace TestC

type Interface
	startup as function cdecl () as short
	shutdown as function cdecl () as short
	construct as any ptr
	destruct as any ptr
	update as any ptr
	test as function cdecl (describeFn as any ptr) as short
	sayHello as function cdecl (name as zstring ptr) as short
end type

end namespace
