
/'
' Generated by Meld Framework, do not modify.  Any changes will be overwritten
' during the next build.
'/

namespace SemVer

type Interface
	startup as function cdecl () as short
	shutdown as function cdecl () as short
	construct as any ptr
	destruct as any ptr
	update as any ptr
	test as any ptr
end type

end namespace
