
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

namespace ConsoleC {

struct Interface {
	short (__cdecl *startup) ();
	short (__cdecl *shutdown) ();
	void* construct;
	void* destruct;
	void* update;
	void* test;
	void  (__cdecl *logMessage) (char*  message );
	void  (__cdecl *logWarning) (char*  id , char*  message , char*  source , int lineNum );
	void  (__cdecl *logError) (char*  id , char*  message , char*  source , int lineNum );
	void  (__cdecl *logSuccess) (char*  id , char*  message , char*  source , int lineNum );
};

}
