
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

namespace Meld {


struct Instance { 
	unsigned long references;
};

struct Interface {
	short (__cdecl *startup) ();
	short (__cdecl *shutdown) ();
	Instance* (*construct) ();
	void (*destruct) (Instance* instancePtr);
	short (*update) (void* instancePtr);
	short (*test) (void* describeFn);
};

}
