
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

namespace Meld {


struct Instance { 
	unsigned long references;
};

struct Interface {
	short (*startup) () __attribute__((cdecl));
	short (*shutdown) () __attribute__((cdecl));
	Instance* (*construct) ();
	void (*destruct) (Instance* instancePtr) __attribute__((cdecl));
	short (*update) (void* instancePtr) __attribute__((cdecl));
	short (*test) (void* describeFn) __attribute__((cdecl));
};

}
