
/*
 * Generated by Meld Framework, do not modify.  Any changes will be overwritten
 * during the next build.
 */

#pragma once

namespace Sys {


struct Interface {
	short (__cdecl *startup) ();
	short (__cdecl *shutdown) ();
	void* construct;
	void* destruct;
	void* update;
	void* test;
	char* (__cdecl *getNewline) ();
	char* (__cdecl *getDirsep) ();
	char* (__cdecl *getModuleExt) ();
	unsigned long long (__cdecl *getTimestamp) ();
	void  (__cdecl *getMacAddress) (char*  addr );
};

}
